### ISSUE TITLE
Connection sans mot de passe

### ISSUE THREAD

**Issue by bouttier** [edirTIC31/edirTIC31_main_courante#10]
Il s’agit de permettre de se connecter en saisissant simplement un nom d’utilisateur (existant ou non, dans ce dernier cas il sera créé à la volé). Cette fonctionnalité serait intégré dans la RadioBox.

**Comment by nim65s** [comment]
oops XD

**Comment by bouttier** [comment]
Fait dans b7680ecdaa1706676b29b0eb97db20c2b37c1b69.
Il faut encore rajouter un peu de JS pour qu’en cliquant sur un utilisateur administrateur, le champ nom d’utilisateur du formulaire de connection soit autocomplété et que le focus soit placé dans le champs password.

**Comment by bouttier** [comment]
Fait dans 8f2e5393052c61d8b6959cb96d368378b5b7ca6e.
