### ISSUE TITLE
Problème de performance sur Raspberry-Pi

### ISSUE THREAD

**Issue by bouttier** [edirTIC31/edirTIC31_main_courante#14]
Le temps de chargement des pages sur R-Pi est très élevé, trop élevé pour une saisie rapide des messages. Il faut donc investiguer afin de voir si le problème peut être résolu ou s’il faut utiliser un autre équipement.

**Comment by l-franck** [comment]
Dans la Minibox, il y a un Odroid avec un RAM disk en eMMC. Je peux voir (quand j'aurai un moment ...) si ca fait la différence.

**Comment by bouttier** [comment]
Résolu : utilisation d’Odroid C1+
