### ISSUE TITLE
indicatif : ignorer la case

### ISSUE THREAD

**Issue by bouttier** [edirTIC31/edirTIC31_main_courante#19]
C’est-à-dire ne pas rajouter un indicatif s’il existe un indicatif identique avec une case différent.
On peut également songer à mettre les indicatifs uniquement en majuscule.

**Comment by nim65s** [comment]
> On peut également songer à mettre les indicatifs uniquement en majuscule.

Ok, mais faut pas obliger les gens à taper en majuscule

**Comment by bouttier** [comment]
Hop, tout en majuscule : 4707a5d36af27b317302cb214d4ec4c7000781db
