### ISSUE TITLE
[main courante][info] Gestionnaire de la CR autrichienne et bavaroise

### ISSUE THREAD

**Issue by GKMN** [edirTIC31/edirTIC31_main_courante#2]
Plop, 

Anthony m'en a parlé lors du Rio Loco, alors je poste le lien ici : http://sourceforge.net/projects/coceso/

Il s'agit d'une plateforme de gestion développé par la Croix-Rouge autrichienne, en collaboration avec la Croix-Rouge bavaroise. Cela à l'air d'être plutôt pas mal vraiment simple d'utilisation.

A voir si on peut s'en inspirer pour le développement de la main courante. C'est ouvert à débat !

**Comment by nim65s** [comment]
C’est plutôt joli et ça ressemble à ce qu’on veut, mais c’est du Java, et c’est sur ma liste noire, désolé :(

**Comment by GKMN** [comment]
Ne t'inquiètes pas, le Java est sur ma liste noire également :D

**Comment by nim65s** [comment]
Au niveau du design, par contre (les petites fenêtres partout), c’est trop pour moi ^^"

**Comment by bouttier** [comment]
Déplacé sur le wiki.
