### ISSUE TITLE
Premier cahier des charges main courante

### ISSUE THREAD

**Issue by l-franck** [edirTIC31/edirTIC31_main_courante#3]
[Objectif]

Création d'une main courante opérationelle (MCO) permettant à plusieurs
opérateurs simultanés d'enregistrer des messages horodatés
dans une base de données. Un message
est défini par un expéditeur, un récipiendaire et un contenu.

Les expéditeurs et récipiendaires sont défini par les
indicatifs radio des équipes correspondantes.

Note : il ne s'agit PAS d'une main courante des victimes

[Fonctionalités]

Note : les fonctionnalités suivantes ne correspondent pas
forcément à des écrans/page web différents

1/ Authentification

* Authentification par login/mot de passe

2/ Configuration

* Ajout/retrait/modification d'utilisateurs
* Définition du nom de l'opération
* Définition des indicatifs radio utilisés + un indicatif 'tous'

3/ Visualisation

Visualisation au fil de l'eau* de la main courante présentée
de manière contra-chronologique (=message le plus récent
d'abord) - pas de modification possible

*fil de l'eau : mise à jour en fonction des saisies des autres opérateurs

4/ Saisie d'un message

Ajout d'un message comprenant : expéditeur, récipiendaire,
corps du message  avec horodatage automatique.

Les expéditeurs et récipiendaires sont identifiés par leurs
indicatifs correspondant (note : on peut utiliser un indicatif
non défini lors de la configuration)

Sur le même écran, affichage au fil de l'eau des messages.

5/ Modification d'un message

Modification d'un message existant avec indication de l'opération
de modification (heure, opérateur) et possibilité de consulter
le 'diff' du corps du message.

Note : si modification simultanée par plusieurs opérateurs,
pas de lock mais prise en compte de la modification la plus
récente.

6/ Effacement d'un message

Effacement complet d'un message avec indication de l'opération
de modification (heure, opérateur). Note : le message est
conservé à l'affichage mais surligné, il ne peut plus être modifié

7/ Cloture de la main courante

Cloture de la main courante avec interdiction de modification/effacement ultérieures
de message et génération d'un PDF d'archive

8/ Génération d'un PDF d'archive

Création d'un PDF des messages de la main courante avec filigrane
indiquant "en cours" si la main courante n'est pas cloturée

[Principes d'interface]

* Saisie complète d'un message au clavier possible (pas exclusivement
à la souris)
* Mode visualisation adapté aux smartphones/tablettes
* Saisie d'un message utilisant le plus possible la saisie prédictive : complétion d'indicatifs,
  et complétion de mots dans le corps du message par rapport à un dictionnaire métier de
  termes courants (PEC, prise en charge, victime, mike, foxtrot, traumatisme, plaie, malaise ...)

[Architecture]

Multi-clients - serveur avec
* Serveur sur système Linux type SoC/Raspberry Pi
* Clients légers (Firefox,Chrome,Internet Explorer,Safari)

[Framework software]

A définir

[Evolutivité]

Intégration de cette main courante opérationelle dans un SITAC incluant
MCO, main courante des victimes, système d'information géographique,
main courante des véhicules etc.

**Comment by bouttier** [comment]
Les specs sont désormais versionné : https://github.com/edirTIC31/edirTIC31_main_courante/blob/master/docs/maincourante/specs.md
