### ISSUE TITLE
Premiers retour sur proto main courante

### ISSUE THREAD

**Issue by l-franck** [edirTIC31/edirTIC31_main_courante#7]
Merci pour le proto

J'ai un peu joué avec le proto (version actuellement sur canelle mais qui n'intègre peut être pas les derniers commits de Julien) voici mes remarques.

Les fautes de frappe :
* Le menu du haut : "saisi" --> "saisie"
* Exp*é*diteur
* R*é*cipiendaire

Les peut-être bugs
* Les messages ne sont pas triés par ordre anti-chrono (du plus récent au plus vieux)
* Le refresh de la page n'est pas automatique suite à la saisie d'un 
second opérateur

Les propositions de modification :
* Dans l'affichage d'un message, est-ce qu'on peut afficher l'heure+date de saisie (à coté des indicatifs  et un peu comme dans le compte rendu ?)
* Dans l'historique d'un message, est-ce qu'on peut afficher l'heure de saisie  (à coté des indicatifs et un peu comme dans le compte rendu  ?)

Merci et bravo !

Est-ce qu'on vise une RC jeudi et on freeze vendredi ?

**Comment by huetjulien** [comment]
Je pense que viser une RC jeudi ça me va. Je vais essayer de bosser dessus un peu ce soir. Merci pour tes retours.
Je vais corriger les problèmes de fautes de frappe.
Mais je ne comprends pas 2 points : 
  - Pour moi c'est ok c'est bien le dernier message qui s'affiche en haut de la liste. je vais ajouter la date et l'heure ça sera peut être plus clair.
 - Qu'entends tu pars "refresh de la page n'est pas automatique suite à la saisie d'un second opérateur" ? C'est lorsque quelqu'un le fait depuis un second pc c'est ça ? Si oui c'est normal ce c'est pas implémenté encore. Je vais rafraîchir automatiquement toutes les 10 secondes. Est-ce que cela te va ?

**Comment by l-franck** [comment]
Concernant les 2 points : 
* Lors de mon test sur canelle les messages étaient classés par ordre alphabétique d'indicatifs (expéditeur first) .... Je viens d'essayer à nouveau et je n'arrive pas à reproduire le bug. Arg. Mais
je suis sûr de mon coup : l'ordre (plus récent d'abord) n'était pas respecté.  
* Pour le refresh: j'utilisais un second navigateur pour "faker" un autre operateur. OK pour un refresh tte les 10 secondes, c'est un bon début !

Merci pour le taf !

De mon coté la plateforme RaspberryPi est opérationnelle, j'ai fait tourner la dernière release de main_courante dessus. Il me reste à voir comment on passe sur un serveur apache2 au lieu du 
serveur de dev.

**Comment by nim65s** [comment]
Tout est bien dit dans la doc: https://docs.djangoproject.com/fr/1.8/howto/deployment/wsgi/modwsgi/

Sinon, voici un exemple de ce que j’utilisais quand j’utilisais apache:

```
<VirtualHost *:80>
    ServerName maincourante.tld
    ServerAlias www.maincourante.tld

    ServerAdmin webmaster@maincourante.tld
    ErrorLog ${APACHE_LOG_DIR}/maincourante.err
    CustomLog ${APACHE_LOG_DIR}/maincourante.log combined

    WSGIScriptAlias / /var/www/edirTIC31_main_courante/edirtic/edirtic/wsgi.py
    WSGIProcessGroup edirtic
    WSGIDaemonProcess edirtic python-path=/var/www/edirTIC31_main_courante/edirtic:/var/www/edirTIC31_main_courante/venv/lib/python3.4/site-packages processes=2 threads=16 maximum-requests=1000 display-name=apache-hello-wsgi

    Alias /static /var/www/edirTIC31_main_courante/edirtic/static_dest

    ExpiresActive On
    ExpiresDefault "access plus 1 year"

    Options -Indexes
</VirtualHost>
```

**Comment by l-franck** [comment]
Merci. De mon cote, j'avais trouve ceci 

http://www.djangobook.com/en/2.0/chapter12.html

Je deploie sur la cible finale vendredi soir. 

Bon voyage.

**Comment by l-franck** [comment]
Hello,

Lionel a testé de son coté, je me permets de relayer ses commentaires envoyés par mail
- Horodatage des messages dans la saisie : s'assurer qu'on est bien en affichage 24h00 et pas AM/PM
- Quand on supprime un message il n'apparait pas comme supprimé dans la saisie (alors que c'est bien le cas dans le compte rendu)
- Il préfère destinataire à récipiendaire
- Il a rencontré un problème de "undefined" (je cite) lors de la saisie d'un message (désolé, je peux pas être plus précis)

En PJ une proposition de logo si vous arrivez à caser ça sur une des pages 

Sinon, il trouve la saisie simple, de bon goût et efficace. 

Merci à vous
L

![logo edir tic 31 marathon de toulouse3](https://cloud.githubusercontent.com/assets/12872713/10648866/59fd5152-7841-11e5-8f47-3b6710cea15e.jpg)

**Comment by l-franck** [comment]
Re,

Je suis repasse sur canelle pour regarder la branche static et franchement, c'est super !
Je n'ai leve de bug. 

Le seul truc que je n'ai pas encore reussi a demontrer c'est l'acces multi-operateur avec refresh de la page, je présume que c'est dans les tuyaux. 

Ce soir, je vais me livrer a une campagne de test intensive et vendredi soir je transfere sur Raspberry (j'attendrai votre feu vert). 

Encore bravo !

**Comment by huetjulien** [comment]
Re,

L'auto refresh est en place.
