### ISSUE TITLE
Caractères accentués dans le code sans détermination de l'encodage

### ISSUE THREAD

**Issue by titixbrest** [edirTIC31/edirTIC31_main_courante#8]
Hello !

J'ai essayé de compiler votre code sous linux (debian jessie en i686)
Je me fais insulter pour chaque fichier contenant un caractère accentué parce que la keymap n'a pas été définie dans les fichiers.

SyntaxError: Non-ASCII character '\xc3' in file /home/thierry/edirTIC31_main_courante/edirtic/maincourante/models.py on line 14, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by titixbrest** [comment]
Voir le pull request :D 

Beau travail !

**Comment by nim65s** [comment]
Salut :)

On fait du python3, l’encodage par défaut est donc utf-8 :)

Le shebang est également inutile dans tout autre fichier que `manage.py`

Et même dans ce cas, on ne met pas `/usr/bin/python` mais `/usr/bin/env python`, afin de lancer l’interpréteur défini par l’environement.
